### PR TITLE
Fixed dependencies

### PR DESCRIPTION
**Pull request by o**
Fixed configurations
Aligned /app files with 2.8 version

### CODE REVIEW

**Comment by utkuaydin** [comment]
@behramcelen, @o: I believe this PR is good to go, no?

**Comment by o** [comment]
@utku This pull request must be tested on a staging environment before the merge. 
Because important files was changed.
Do you have any doubt about bad smell code?

**Comment by utkuaydin** [comment]
@o I can't see anything which could go wrong but if you want it to age for a little while, that's fine by me.

**Comment by behram** [comment]
@o i locally solved conflicts and merged. thanks 👏

**Pull request merged**
