### PR TITLE
Hosting journal with custom domain

### PR DESCRIPTION
**Pull request by hmert**
- [x] archive

- [x] board

- [x] issue

- [x] article

- [x] pages

- [x] contacts

- [x] posts

- [x] announcement

### CODE REVIEW

**Comment by hmert** [comment]
@behram I have some bugs... Article submission and journal localte src/Ojs/SiteBundle/Controller/JournalController.php:154

**Comment by behram** [comment]
i am testing this branch locally

**Comment by behram** [comment]
i tested branch locally too. works correcly but code quality is a little low. we can revise after merge

**Comment by behram** [comment]
one day we will revise site bundle fully that time i will revise this changes too. now i am merging branch. thanks @hmert 👏

**Pull request merged**
